### ISSUE TITLE
objectident.py getting it to only write once to my file "seen.txt"

### ISSUE THREAD

**Issue by SamMakesIt** [SamMakesIt/pokedex#2]
This should be fairly easy to check if foundClass is in seen.txt, if not write foundClass into file "seen.txt" if foundClass exists in seen.txt dont do anything. I have it as print already seen in the terminal for testing 

def recordFound(recordDex):
    foundDex = foundClass
    recordDex = os.path.abspath("seen.txt")
    with open(recordDex, "a+") as f:
        if foundClass in f.read():
            print("already seen")
        else:
            f.write(foundClass + "\n")

**Comment by KevinMSampson** [comment]
@SamMakesIt 
Was this resolved?

**Comment by SamMakesIt** [comment]
Yeah I should probably close the issue LMAO
